version: '3.6'

services:
  path-finder-cli:
    build: ./src/
    image: path-finder-cli:latest
    volumes:
    #Configs are not supported in local mode
    - ${PWD}/graph.txt:/graph.txt
    shm_size: 4G
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    environment:
      - USE_DEBUGGER=enabled
    stdin_open: true
    tty: true